[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fish_tracker"
version = "0.1.0"
description = "A modular computer vision pipeline for detecting and tracking fish in underwater video recordings."
authors = [
    { name = "Lina Khodja" }
]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "matplotlib",
    "numpy",
    "opencv-contrib-python",
    "pydantic>=2.0,<3.0",
    "scipy",
]

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "pytest",
]

[project.urls]
Source = "https://github.com/l-k-11235/fish-tracker"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ["py39"]
